import type { Metadata } from 'next'
import HeaderWrapper from '../components/layout/HeaderWrapper'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background ">
        <HeaderWrapper />
        {children}
      </body>
    </html>
  )
}
